apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: skupper-operator
  namespace: openshift-operators
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: skupper-operator
  startingCSV: skupper-operator.v1.2.2
  source: redhat-operators
  sourceNamespace: openshift-marketplace